name: Fast-DDS continuous integration

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:

  call-workflow-passing-data:
    uses: ./.github/workflows/reusable-github-ci.yml
    with:
      os: "[\"ubuntu-22.04\",\"ubuntu-20.04\",\"windows-2022\",\"windows-2019\",\"macos-12\",\"macos-11\"]"
      config: "[\"debug\",\"release\"]"
