name: Fast-DDS continuous integration

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:

  Running-CI:
    uses: ./.github/workflows/reusable-github-ci.yml
    with:
      os: "[\"ubuntu-22.04\",\"windows-2022\",\"macos-12\"]"
      config: "[\"release\"]"
      vs_toolset: "[\"v143\",\"v142\",\"v141\"]"
  
